name: Go
on:
  - push
  - schedule:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - run: sudo apt-get update && sudo apt-get install -y expect

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -race -v .

    - name: Check Format
      run: |
        diff -u <(echo -n) <(gofmt -d -e -s .)

    - name: Run tests
      run: |
        go test -count 1 -timeout 30s ./...

    - name: Smoke test
      run: |
        ./rivet
        ./rivet version

    - name: Run end to end test
      run: |
        cd etc
        ./test-dkc.sh ../rivet
      env:
        DKC_API_KEY: ${{ secrets.DKC_API_KEY }}
